spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/github_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

github.client.id=Ov23liNDgtw2N1vt6zVS
github.client.secret=60d90a36d3221098d8fba6b581654a8177c70c70
github.redirect.uri=http://localhost:8080/auth/github/callback

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

jira.base-url=https://samcode2212-1765254245608.atlassian.ne
jira.email=samcode2212@gmail.com
jira.api-token=ATATT3xFfGF0vcSLZvgBQdwSNRC-SsdSMaI70HGBwMc19eTl7LsPMIXegQXMHtaQQlf2KwzaP1HDHB6I0eFv5OgvtlOirX2KEHo0izDgBfxfFkRWtFGFFl0nku9FDQ5_Fm38yhIUaPOg_Uy3_4gX4Zt_Y72FjihIsdUrMtspywCDqd6BNfkCXmc=BC864793

spring.main.allow-bean-definition-overriding=true
