spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/github_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

github.client.id=Ov23liNDgtw2N1vt6zVS
github.client.secret=c09f02cc53c2699987caaa86f8faee8cc61a302f
github.redirect.uri=http://localhost:8080/auth/github/callback

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

jira.base-url=https://samcode2212.atlassian.net
jira.email=samcode2212@gmail.com
jira.api-token=ATATT3xFfGF0E7cbtVyn3gLHlbUrXzsg9SJaCTd9CbxT59VA5wT0PEfFHPRAHIdcWx37lf570Wi63v7MVLb4veu_6y7gDd-G4R8WEr5nEjiVZ0hGANQQYh1h7wUXnVeyoQloJow9VOqzerIW_YXi1Uh7s_Jq5F21hWlanT_XJOx-vQZDZx0qN2o=16540189

spring.main.allow-bean-definition-overriding=true
