spring.application.name=backend
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/github_tracker}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
github.client.id=${GITHUB_CLIENT_ID:}
github.client.secret=${GITHUB_CLIENT_SECRET:}
github.redirect.uri=${GITHUB_REDIRECT_URI:http://localhost:8080/auth/github/callback}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
jira.base-url=${JIRA_BASE_URL:https://samcode2212.atlassian.net/}
jira.email=${JIRA_EMAIL:}
jira.api-token=${JIRA_API_TOKEN:}
spring.main.allow-bean-definition-overriding=true
